name: Aurora - Publish API and UI
on:
  push:
    branches:
      - feature/pipeline
env:
  AZURE_WEBAPP_NAME: appaurora
  
  AZURE_BACKEND_WEBAPP_PACKAGE_PATH: '.'
  AZURE_FRONTEND_WEBAPP_PACKAGE_PATH: Frontend\Frontend.Web\published

  BACKEND_WORKING_DIRECTORY: Backend\Backend.API
  FRONTEND_WORKING_DIRECTORY: Frontend\Frontend.Web
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore "${{ env.BACKEND_WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.BACKEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.BACKEND_WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.BACKEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_BACKEND_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backend
        path: ${{ env.AZURE_BACKEND_WEBAPP_PACKAGE_PATH }}

    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore "${{ env.FRONTEND_WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.FRONTEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.FRONTEND_WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.FRONTEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FRONTEND_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend
        path: ${{ env.AZURE_FRONTEND_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_BACKEND_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3FB15A912AF54FB69E6F03E58B35D104 }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: ${{ env.AZURE_FRONTEND_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3FB15A912AF54FB69E6F03E58B35D104 }}
          package: ${{ env.AZURE_FRONTEND_WEBAPP_PACKAGE_PATH }}
    