name: Aurora - Publish API and UI
on:
  push:
    branches:
    - feature/pipeline
env:
  AZURE_WEBAPP_NAME: appaurora
  
  FRONTEND_OUTPUT_PACKAGE_PATH: .\frontend-output\
  FRONTEND_ARTIFACT_PATH: .\frontend-output\frontend

  BACKEND_OUTPUT_PACKAGE_PATH: .\backend-output\
  BACKEND_ARTIFACT_PATH: .\backend-output\backend

  BACKEND_WORKING_DIRECTORY: .\src\Backend\Backend.API
  FRONTEND_WORKING_DIRECTORY: .\src\Frontend\Frontend.Web

  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore "${{ env.BACKEND_WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.BACKEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.BACKEND_WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.BACKEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.BACKEND_OUTPUT_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backend
        path: ${{ env.BACKEND_OUTPUT_PACKAGE_PATH }}

    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore "${{ env.FRONTEND_WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.FRONTEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.FRONTEND_WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.FRONTEND_WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.FRONTEND_OUTPUT_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend
        path: ${{ env.FRONTEND_OUTPUT_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from Frontend build job
        uses: actions/download-artifact@v3
        with:
          name: backend
          path: ${{ env.BACKEND_OUTPUT_PACKAGE_PATH }}
      - name: List artifact files
        run: |
            ls ${{ env.BACKEND_OUTPUT_PACKAGE_PATH }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.BACKEND_ARTIFACT_PATH }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE_BACKEND }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: ${{ env.FRONTEND_OUTPUT_PACKAGE_PATH }}
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.FRONTEND_ARTIFACT_PATH }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FRONTEND }}
    