name: Aurora - Publish API and UI
on:
  push:
    branches:
    - feature/pipeline
env:
  AZURE_WEBAPP_NAME: appaurora
  
  FRONTEND_OUTPUT_PACKAGE_PATH: .\frontend-output\
  BACKEND_OUTPUT_PACKAGE_PATH: .\backend-output\

  BACKEND_WORKING_DIRECTORY: .\src\Backend\Backend.API
  FRONTEND_WORKING_DIRECTORY: .\src\Frontend\Frontend.Web

  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Create folder for Backend Artifacts
        run: mkdir 'src\Backend\Backend.API'

      - name: Create folder for Frontend Artifacts
        run: mkdir 'src\Frontend\Frontend.Web'
