name: Aurora - Publish API and UI
on:
  push:
    branches:
    - feature/pipeline
env:
  AZURE_WEBAPP_NAME: appaurora
  
  FRONTEND_OUTPUT_PACKAGE_PATH: .\frontend-output\
  BACKEND_OUTPUT_PACKAGE_PATH: .\backend-output\

  BACKEND_WORKING_DIRECTORY: .\src\Backend\Backend.API
  FRONTEND_WORKING_DIRECTORY: .\src\Frontend\Frontend.Web

  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x

jobs:
  prepare:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: List
      run: dir

    - name: Create folder
      run: mkdir -p src/Backend/Backend.API
